[package]
authors = ["Sayan Nandan <nandansayan@outlook.com>"]
categories = []
description = "Official Rust client driver for Skytable"
documentation = "https://docs.rs/skytable"
edition = "2018"
keywords = ["skytable", "driver", "client", "database", "nosql"]
license = "Apache-2.0"
name = "skytable"
readme = "README.md"
repository = "https://github.com/skytable/client-rust"
version = "0.5.0-alpha.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
aio-ssl = ["tokio-openssl", "openssl"]
aio-sslv = ["tokio-openssl", "openssl/vendored"]
async = ["bytes", "tokio"]
const-gen = []
dbg = []
default = ["sync"]
ssl = ["openssl"]
sslv = ["openssl/vendored"]
sync = []

[dependencies]
bytes = {version = "1.0.1", optional = true}
openssl = {version = "0.10.35", optional = true}
tokio = {version = "1.9.0", features = ["net", "io-util", "io-std"], optional = true}
tokio-openssl = {version = "0.6.2", optional = true}
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
