[package]
name = "skytable"
version = "0.3.0-alpha.1"
authors = ["Sayan Nandan <nandansayan@outlook.com>"]
edition = "2018"
readme = "README.md"
description = "Official Rust client driver for Skytable"
license = "Apache-2.0"
documentation = "https://docs.rs/skytable"
repository = "https://github.com/skytable/client-rust"
categories = []
keywords = ["skytable", "driver", "client", "database", "nosql"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["sync"]
async = ["bytes", "tokio"]
sync = []
dbg = []

[dependencies]
bytes = {version="1.0.1", optional=true}
tokio = {version = "1.5.0", features = ["net", "io-util", "io-std"], optional=true}

[dev-dependencies]
tokio = {version="1.5.0", features=["rt-multi-thread", "macros"]}

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]