[package]
name = "sky-derive"
version = "0.0.1"
edition = "2018"
license = "Apache-2.0"
description = "Derive macros for Skyhash"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
